<?php

 use KumbiaPHP\View\View; ?>
<div id="k2_debug_container">
    <ul class="k2_debug_tabs">
        <li id="k2_debug_queries">
            <h5>Consultas SQL: <?php echo is_array($queries) ? count($queries) : 0 ?></h5>
            <div class="k2_debug_info">                
                <?php if (is_array($queries) && count($queries)): ?>
                    <ul class="k2_debug_queries_list">
                        <?php foreach ($queries as $query): ?>
                            <li>
                                <code><?php eh($query['query']) ?></code>
                                <br/>Parametros: (
                                <?php foreach ((array) $query['parameters'] as $index => $value): ?>
                                    <b> <?php eh($index) ?></b> => <?php eh($value) ?>,
                                <?php endforeach; ?> );
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </div>
        </li>
        <li>
            <h5>Archivos Incluidos: <?php echo count(get_included_files()) ?></h5>
            <div class="k2_debug_info">
                <ul>                    
                    <?php foreach ((array) get_included_files() as $file): ?>
                        <li><?php eh($file) ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </li>
        <li>
            <h5>Petición: <?php echo View::app()->getRequestUrl() ?></h5>
            <div class="k2_debug_info">
                <ul>
                    <li><b>Módulo:</b> <?php eh(View::app()->getCurrentModuleUrl()) ?> => <?php eh(View::app()->getCurrentModule()) ?></li>
                    <li><b>Controlador:</b> <?php eh(View::app()->getCurrentController()) ?></li>
                    <li><b>Acción:</b> <?php eh(View::app()->getCurrentAction()) ?></li>
                    <li><b>Parametros:</b> <?php echo print_r(View::app()->getCurrentParameters(), true) ?></li>
                </ul>
            </div>
        </li>
        <li>
            <h5>Respuesta: Status = <?php eh($status) ?></h5>
            <div class="k2_debug_info">
                <ul>
                    <li><b>Charset:</b> <?php eh($charset) ?></li>
                    <li><b>Estado:</b> <?php eh($status) ?></li>
                    <?php foreach ($headers as $i => $h): ?>
                        <?php if (is_numeric($i)): ?>
                            <li><b><?php eh($h) ?></b></li>
                        <?php else: ?>
                            <li><b><?php eh($i) ?>:</b> <?php eh($h) ?></li>
                        <?php endif ?>
                    <?php endforeach ?>
                </ul>
            </div>
        </li>
        <li>
            <h5>Variables Volcadas: <?php echo count($dumps) ?></h5>
            <div class="k2_debug_info">
                <ul>                    
                    <?php foreach ((array) $dumps as $title => $var): ?>
                        <li><b><?php eh($title) ?></b><pre><?php var_dump($var) ?></pre></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </li>
        <li>
            <h5>                
                <?php echo round((microtime(1) - START_TIME), 4) . ' seg. / ' . number_format(memory_get_usage() / 1048576, 2) . ' MB'; ?>
            </h5>
        </li>
    </ul>
</div>
<style>
    #k2_debug_container{
        position: fixed;
        height: 50px;
        width: 100%;
        background-color: #F5F5F5;
        bottom: 0px;
        left: 0px;
        box-shadow: 0 0px 5px #000;
    }

    .k2_debug_tabs{
        margin: 0px 10px;
        padding: 0;
        white-space: nowrap
    }
    .k2_debug_tabs li{
        padding: 5px;
        vertical-align: top;
        display: inline-block;
        border-right: 1px solid #c1c0c0;
        width: 15%;
        position: relative;
        white-space: normal;
        min-height: 45px
    }
    .k2_debug_tabs li h5{
        margin: 0px;
        padding: 0px;
    }

    #k2_debug_container .k2_debug_info ul{
        width: 100%;
    }
    #k2_debug_container .k2_debug_info li{
        border-bottom: 1px solid #c1c0c0;
        padding: 10px;
        width: 100%;
        min-height: 20px
    }

    .k2_debug_tabs > li:hover .k2_debug_info{
        display: block;
    }
    .k2_debug_info{
        display: none;
        position: fixed;
        width: 100%;
        left: 0px;
        background-color: #e6e4e4;
        box-shadow: 0 0px 5px #000;
        bottom: 49px;
        max-height: 400px;
        overflow: auto;
    }
</style>
